---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.58.2
    validate: true

- name: docker
  image: plugins/docker
  settings:
    registry: registry.squizduos.ru
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.squizduos.ru/channel11/web
    tags: latest

- name: notify
  image: appleboy/drone-telegram
  settings:
    to: 
      from_secret: notify_telegram_id
    token:
      from_secret: notify_telegram_token
    message: >
      {{repo.owner}}/{{repo.name}}: \[{{build.status}}] Build {{build.number}}
      {{commit.author}} pushed to {{commit.branch}} {{commit.sha}}: `{{commit.message}}`
      Build started at {{datetime build.started "2006-Jan-02T15:04:05Z" "GMT+2"}} finished at {{datetime build.finished "2006-Jan-02T15:04:05Z" "GMT+2"}}.

trigger:
  branch:
  - master