pipeline:
  build:
    image: monachus/hugo:v0.57-2
    commands:
     - hugo check
     - hugo
    when:
      branch: [ master ]
  deploy:
    image: plugins/docker
    registry: rg.nl-ams.scw.cloud
    repo: squizduos/channel11_info
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: [ master ]
  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token ]
    token: ${TELEGRAM_TOKEN}
    to: 57439615
    message: Сборка www.channel11.info завершена.
    when:
      branch: [ master ]
