---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    registry: 
      from_secret: docker_registry
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: channel11/new_blog
    tags: latest

- name: telegram
  image: appleboy/drone-telegram
  to: 
    from_secret: notify_telegram_id
  token:
    from_secret: notify_telegram_token
  message: Сборка channel11/new_blog завершена.

trigger:
  branch:
  - master