---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    registry: registry.squizduos.ru
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.squizduos.ru/channel11/new_blog
    tags: latest

- name: telegram
  image: appleboy/drone-telegram
  settings:
    to: 
      from_secret: notify_telegram_id
    token:
      from_secret: notify_telegram_token
    message: Сборка channel11/new_blog завершена.

trigger:
  branch:
  - master