---
kind: pipeline
name: default

steps:
- name: build
  image: monachus/hugo:v0.58-2
  commands:
    - hugo check
    - hugo
  when:
    event:
    - push

- name: docker-publish
  image: plugins/docker
  settings:
    registry: 
      from_secret: docker_registry
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: channel11/new_blog
    tags: latest
  when:
    event:
    - push

- name: telegram
  image: appleboy/drone-telegram
  to: 
    from_secret: notify_telegram_id
  token:
    from_secret: notify_telegram_token
  message: Сборка channel11/new_blog завершена.
  when:
    event:
    - push
